version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8084:8084"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: unless-stopped